# 1. Obtención de datos (Consumo de la API)

Selecciona una API pública de libre acceso.

Realiza la petición utilizando la librería requests y convierte la respuesta a un DataFrame de Pandas.

In [44]:
import requests
import pandas as pd

url = "https://rickandmortyapi.com/api/character"
respuesta = requests.get(url)
datos = respuesta.json()

df = pd.DataFrame(datos["results"])

print(df["name"].head())
print(df.dtypes)

0    Rick Sanchez
1     Morty Smith
2    Summer Smith
3      Beth Smith
4     Jerry Smith
Name: name, dtype: object
id           int64
name        object
status      object
species     object
type        object
gender      object
origin      object
location    object
image       object
episode     object
url         object
created     object
dtype: object

# 2. Diagnóstico y transformación de variables (Importante si tus datos son de texto, verifica los tipos de datos)

Utiliza .info() y .describe() para examinar tu DataFrame.

¿Qué pasa si tus datos son muy textuales? Si la API elegida devuelve principalmente texto (nombres, descripciones, categorías), deberás preparar y transformar tus datos antes de analizarlos. Cuentas con dos opciones (puedes aplicar ambas):

          - Conversión de tipos: Si hay números o fechas disfrazados de texto, conviértelos al tipo correcto (int, float, datetime) usando .astype() o pd.to_numeric().

           -Creación de variables numéricas (Ingeniería de características): Genera nuevas columnas numéricas a partir del texto. Por ejemplo: 
           
           -calcular la longitud de los caracteres de un campo de texto (como el largo de un título usando .apply(len)), contar cuántas palabras tiene una descripción, o contar la frecuencia de elementos en una lista anidada.

In [45]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        20 non-null     int64
 1   name      20 non-null     object
 2   status    20 non-null     object
 3   species   20 non-null     object
 4   type      20 non-null     object
 5   gender    20 non-null     object
 6   origin    20 non-null     object
 7   location  20 non-null     object
 8   image     20 non-null     object
 9   episode   20 non-null     object
 10  url       20 non-null     object
 11  created   20 non-null     object
dtypes: int64(1), object(11)
memory usage: 2.0+ KB

             id
count  20.00000
mean   10.50000
std     5.91608
min     1.00000
25%     5.75000
50%    10.50000
75%    15.25000
max    20.00000

In [66]:
#Como en su mayoría es texto lo que me devuelve entonces voy a hacer:  Creación de variables numéricas

#la idea es contar cuantos carácteres tiene cada elemento para poder tener datos numéricos:

df["conversion_name"] = df["name"].apply(len)


df["conversion_status"] = df["status"].apply(len)

df["conversion_species"] = df["species"].apply(len)

df["conversion_type"] = df["type"].apply(len)

df["conversion_gender"] = df["gender"].apply(len)

df["conversion_origin"] = df["origin"].apply(len) #nos devuelve el numero de claves del diccionario

df["conversion_location"] = df["location"].apply(len) #nos devuelve el número de claves del diccionario

df["conversion_image"] = df["image"].apply(len)
 
df["conversion_episode"] = df["episode"].apply(len)

df["conversion_url"] = df["url"].apply(len)
print(df[["url", "conversion_url"]]) 

df["conversion_created"] = df["created"].apply(len)
print(df[["created", "conversion_created"]]) 

#revisé absolutamente todos los prints para verificar que el conteo estuviera correcto o al menos tuviera sentido, pero solo dejé el del final
#para fines prácticos

                                             url  conversion_url
0    https://rickandmortyapi.com/api/character/1              43
1    https://rickandmortyapi.com/api/character/2              43
2    https://rickandmortyapi.com/api/character/3              43
3    https://rickandmortyapi.com/api/character/4              43
4    https://rickandmortyapi.com/api/character/5              43
5    https://rickandmortyapi.com/api/character/6              43
6    https://rickandmortyapi.com/api/character/7              43
7    https://rickandmortyapi.com/api/character/8              43
8    https://rickandmortyapi.com/api/character/9              43
9   https://rickandmortyapi.com/api/character/10              44
10  https://rickandmortyapi.com/api/character/11              44
11  https://rickandmortyapi.com/api/character/12              44
12  https://rickandmortyapi.com/api/character/13              44
13  https://rickandmortyapi.com/api/character/14              44
14  https://rickandmortyapi.com/api/character/15              44
15  https://rickandmortyapi.com/api/character/16              44
16  https://rickandmortyapi.com/api/character/17              44
17  https://rickandmortyapi.com/api/character/18              44
18  https://rickandmortyapi.com/api/character/19              44
19  https://rickandmortyapi.com/api/character/20              44
                     created  conversion_created
0   2017-11-04T18:48:46.250Z                  24
1   2017-11-04T18:50:21.651Z                  24
2   2017-11-04T19:09:56.428Z                  24
3   2017-11-04T19:22:43.665Z                  24
4   2017-11-04T19:26:56.301Z                  24
5   2017-11-04T19:50:28.250Z                  24
6   2017-11-04T19:59:20.523Z                  24
7   2017-11-04T20:03:34.737Z                  24
8   2017-11-04T20:06:54.976Z                  24
9   2017-11-04T20:19:09.017Z                  24
10  2017-11-04T20:20:20.965Z                  24
11  2017-11-04T20:32:33.144Z                  24
12  2017-11-04T20:33:30.779Z                  24
13  2017-11-04T20:51:31.373Z                  24
14  2017-11-04T20:56:13.215Z                  24
15  2017-11-04T21:12:45.235Z                  24
16  2017-11-04T22:21:24.481Z                  24
17  2017-11-04T22:25:29.008Z                  24
18  2017-11-04T22:28:13.756Z                  24
19  2017-11-04T22:34:53.659Z                  24

# 3. Calidad de datos y segmentación

Identifica la presencia de datos faltantes (NaN) y reporta qué porcentaje representan en las columnas afectadas.

Realiza al menos una agrupación o conteo de valores (.value_counts()) para entender cómo se distribuyen tus variables categóricas o de texto.

In [47]:
#viendo si hay valores NaN

df.isna()

,id,name,status,species,type,gender,origin,location,image,episode,...,conversion_status,conversion_species,conversion_type,conversion_gender,conversion_origin,conversion_location,conversion_image,conversion_episode,conversion_url,conversion_created
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# Nota:

En mi caso, no hay valores NaN

In [55]:
df["species"].value_counts() #distribución de species

species
Human    15
Alien     5
Name: count, dtype: int64

In [56]:
df["name"].value_counts() #distribución de name

name
Rick Sanchez                 1
Morty Smith                  1
Summer Smith                 1
Beth Smith                   1
Jerry Smith                  1
Abadango Cluster Princess    1
Abradolf Lincler             1
Adjudicator Rick             1
Agency Director              1
Alan Rails                   1
Albert Einstein              1
Alexander                    1
Alien Googah                 1
Alien Morty                  1
Alien Rick                   1
Amish Cyborg                 1
Annie                        1
Antenna Morty                1
Antenna Rick                 1
Ants in my Eyes Johnson      1
Name: count, dtype: int64

# 4. Análisis estadístico: Medidas de localización

Selecciona al menos una variable numérica de tu DataFrame (puede ser una variable nativa de la API o una variable numérica que hayas creado tú a partir del texto, como la longitud de un campo).

     Para esta variable, calcula e interpreta:
Medidas de tendencia Central: Media (promedio), Mediana y Moda.

Medidas de posición: Los cuartiles (Q1, Q2, Q3) para entender cómo se distribuyen los datos en un diagrama de caja conceptual.

In [80]:
#calculando media del "url"
media = df["conversion_url"].mean()
print(f"La media de los id es: {media}")

mediana = df["conversion_url"].median()
print(f"La mediana de los datos convertidos a número del url es: {mediana}")


moda = df["conversion_url"].mode()[0] #el "[0]" hace que no se imprima el cero, que sería el id de la moda, ya que a veces hay más de una
print(f"La moda de los datos convertidos a número del url es: {moda}")



Q1= df["conversion_url"].quantile(0.25)
Q2 = df["conversion_url"].quantile(0.50)
Q3 = df["conversion_url"].quantile(0.75)
IQR = Q3 - Q1

print(f"el Q1 es: {Q1}")
print(f"el Q2 es: {Q2}")
print(f"el Q3 es: {Q3}")
print(f"IQR: {IQR}")

La media de los id es: 43.55
La mediana de los datos convertidos a número del url es: 44.0
La moda de los datos convertidos a número del url es: 44
el Q1 es: 43.0
el Q2 es: 44.0
el Q3 es: 44.0
IQR: 1.0

Reflexión Final (Mínimo 5 líneas): Incluye al final una breve conclusión respondiendo a las preguntas guía sobre las dificultades en la transformación de datos y el cálculo de tus medidas de localización.
                  ¿Qué dificultades tuviste para adaptar o transformar los datos de la API antes de poder calcular las medidas de localización?
                 ¿Qué te pareció más interesante de la estructura de los datos que recibiste?


## respuesta:
Al principio tuve dificultades al momento de transformar los datos provenientes de la API, porque al intentar aplicar funciones como la longitud de caracteres en la columna “name” surgieron errores relacionados con el tipo de datos. Por lo que me puse a revisar la estructura del DataFrame donde (después de un tiempo) me di cuenta de que Pandas interpretaba algunos valores como tipos no compatibles para hacer por ejemplo: 
df["conversion_name"] = df["name"].apply(len).
El error que salía en la terminal era que había datos del tipo "float" en la variable "name" pero no tenía sentido, así que después de mucho rato de hacer pruebas, opté por borrar todo y volver a ejecutar lo mismo desde el inicio, y ahora sí funcionó, aún no me explico el error... Porque el código era el mismo que la segunda vez que lo intenté y sí funcionó.
De resto todo bien, sólo errores de principiante de olvidarme usar por ejemplo: "conversion_url" para calcular la media, y usar "url" y toparme con un error.


Personalmente lo que más me parece genuinamente bonito es que al dataset se le puede "sacar" la información, hacer que nos hablen los datos. Y en este caso lo que más me pareció interesante fueron los diccionarios que me arrojó al inicio, y que para poder usarlos para los cálculos, contara el número de variables.